# Generated by Django 5.2.17 on 2026-09-22 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('ACTIVE', 'Active'), ('STOPPED', 'Stopped')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='assignments.assignment')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_points', to='tracking.trackingsession')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['assignment', 'status'], name='tracking_tr_assignm_f014e4_idx'),
        ),
        migrations.AddIndex(
            model_name='locationpoint',
            index=models.Index(fields=['session', 'recorded_at'], name='tracking_lo_session_7f60ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationpoint',
            constraint=models.UniqueConstraint(fields=('session', 'recorded_at'), name='unique_session_recorded_at'),
        ),
    ]
