# Generated by Django 5.2.17 on 2026-09-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_idolevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idolevent',
            name='event_type',
            field=models.CharField(choices=[('TRACKING_STARTED', 'Tracking Started'), ('TRACKING_STOPPED', 'Tracking Stopped'), ('ASSIGNMENT_CREATED', 'Assignment Created'), ('ASSIGNMENT_HANDOVER', 'Assignment Handover'), ('ZONE_ENTERED', 'Zone Entered'), ('HOLDING_POINT_ENTERED', 'Holding Point Entered'), ('HOLDING_POINT_EXITED', 'Holding Point Exited'), ('VISARJAN_REACHED', 'Visarjan Site Reached'), ('IMMERSION_COMPLETED', 'Immersion Completed'), ('REPORT_GENERATED', 'Report Generated')], db_index=True, max_length=50),
        ),
    ]
