# Generated by Django 5.2.9 on 2026-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_idolevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idolevent',
            name='event_type',
            field=models.CharField(choices=[('REACHED_SITE', 'Reached Site'), ('TRACKING_STARTED', 'Tracking Started'), ('TRACKING_STOPPED', 'Tracking Stopped'), ('ASSIGNMENT_CREATED', 'Assignment Created'), ('ASSIGNMENT_HANDOVER', 'Assignment Handover'), ('ASSIGNMENT_ENDED', 'Assignment Ended'), ('ASSIGNMENT_FORCE_ENDED', 'Assignment Force Ended'), ('PROCESSION_ADMIN_TERMINATED', 'Procession Admin Terminated'), ('ZONE_ENTERED', 'Zone Entered'), ('HOLDING_POINT_ENTERED', 'Holding Point Entered'), ('HOLDING_POINT_EXITED', 'Holding Point Exited'), ('VISARJAN_REACHED', 'Visarjan Site Reached'), ('IMMERSION_COMPLETED', 'Immersion Completed'), ('VISARJAN_NOT_DONE', 'Visarjan Not Done'), ('SENT_TO_HOLDING', 'Sent to Holding'), ('RETURNED_TO_ORIGIN', 'Returned to Origin'), ('REPORT_GENERATED', 'Report Generated')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('ACTIVE', 'Active'), ('STOPPED', 'Stopped'), ('ADMIN_TERMINATED', 'Admin Terminated')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
