# Generated by Django on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_remove_locationpoint_point_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['status', '-started_at'], name='tracking_tr_status_4f0ba7_idx'),
        ),
    ]
