# Generated by Django 5.2.17 on 2026-09-22 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idols', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('handover_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('constable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('handover_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_assignments', to=settings.AUTH_USER_MODEL)),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='idols.idol')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['idol', 'is_active'], name='assignments_idol_id_acbc23_idx'), models.Index(fields=['constable', 'is_active'], name='assignments_constab_703bd2_idx'), models.Index(fields=['started_at', 'ended_at'], name='assignments_started_7c820a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('constable',), name='unique_active_constable_assignment'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('idol',), name='unique_active_idol_assignment')],
            },
        ),
    ]
