# Generated by Django 5.2.17 on 2026-09-22 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStationBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ps_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('zone', models.CharField(db_index=True, max_length=100)),
                ('division', models.CharField(db_index=True, max_length=100)),
                ('first_unique_id', models.CharField(blank=True, max_length=50)),
                ('starting_gpid_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Police Station Boundary',
                'verbose_name_plural': 'Police Station Boundaries',
                'ordering': ['ps_name'],
            },
        ),
        migrations.CreateModel(
            name='BoundaryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_events', to='idols.idol')),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='geography.policestationboundary')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['idol', 'timestamp'], name='geography_b_idol_id_54f2b9_idx')],
            },
        ),
    ]
