# Generated by Django 5.2.9 on 2026-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_policestationboundary_boundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_bucket', models.DecimalField(db_index=True, decimal_places=4, max_digits=9)),
                ('lon_bucket', models.DecimalField(db_index=True, decimal_places=4, max_digits=9)),
                ('place_name', models.CharField(max_length=255)),
                ('police_station', models.CharField(default='Jurisdiction unavailable', max_length=150)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('division', models.CharField(blank=True, max_length=100)),
                ('raw_address', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geocoding Cache',
                'verbose_name_plural': 'Geocoding Cache Entries',
                'indexes': [models.Index(fields=['lat_bucket', 'lon_bucket'], name='geography_g_lat_buc_5d16c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('lat_bucket', 'lon_bucket'), name='unique_geocoding_lat_lon_bucket')],
            },
        ),
    ]
