# Generated by Django 5.2.9 on 2026-09-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_custom_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MAIN_OFFICER', 'Main Officer / System Admin'), ('SYS_ADMIN', 'System Admin'), ('ACP', 'ACP / Senior Officer'), ('SHO', 'Station House Officer'), ('CONSTABLE', 'Constable / Ground Staff')], db_index=True, default='CONSTABLE', max_length=20),
        ),
    ]
