# Generated by Django 5.2.17 on 2026-09-24 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MAIN_OFFICER', 'Main Officer / System Admin'), ('SYS_ADMIN', 'System Admin'), ('ACP', 'ACP / Senior Officer'), ('SHO', 'Station House Officer'), ('CONSTABLE', 'Constable / Ground Staff')], db_index=True, default='CONSTABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='RolePermissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MAIN_OFFICER', 'Main Officer / System Admin'), ('SYS_ADMIN', 'System Admin'), ('ACP', 'ACP / Senior Officer'), ('SHO', 'Station House Officer'), ('CONSTABLE', 'Constable / Ground Staff')], db_index=True, max_length=20, unique=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Permission Template',
                'verbose_name_plural': 'Role Permission Templates',
                'ordering': ['role'],
            },
        ),
    ]
