# Generated by Antigravity on 2026-09-25

from django.db import migrations


ROLE_DATA = [
    {
        'role': 'SUPER_ADMIN',
        'description': 'Full, unrestricted administrative authority across the entire Ganesh Live Tracking platform, user directory, role permissions, and system audit logs.',
        'permissions': [
            'view_dashboard', 'view_idols', 'view_gpids', 'view_police_stations',
            'view_holding_points', 'view_visarjan_points', 'view_live_map', 'view_processions',
            'view_journey', 'view_tracking_history', 'ingest_telemetry', 'view_officer_locations',
            'view_assignments', 'assign_field_officers', 'create_assignments', 'reassign_assignments',
            'manage_assignments', 'handover_duty', 'view_reports', 'generate_reports',
            'export_reports', 'view_audit_logs', 'view_alerts', 'manage_geography',
            'manage_users', 'manage_permissions', 'manage_roles', 'manage_role_templates',
        ]
    },
    {
        'role': 'MAIN_OFFICER',
        'description': 'Headquarters command and operational control across all zones and police stations, live monitoring, assignment oversight, and reports.',
        'permissions': [
            'view_dashboard', 'view_live_map', 'view_gpids', 'view_idols', 'view_processions',
            'view_police_stations', 'view_reports', 'generate_reports', 'view_alerts',
            'view_holding_points', 'view_visarjan_points', 'view_tracking_history', 'view_journey',
            'assign_field_officers', 'create_assignments', 'reassign_assignments', 'manage_assignments',
            'handover_duty', 'ingest_telemetry', 'view_officer_locations', 'manage_users',
            'manage_permissions', 'manage_geography', 'export_reports', 'view_audit_logs', 'view_assignments',
        ]
    },
    {
        'role': 'SYS_ADMIN',
        'description': 'Zone-level administrator with authority over user accounts, assignment coordination, and monitoring within their assigned zone.',
        'permissions': [
            'view_dashboard', 'view_live_map', 'view_gpids', 'view_idols', 'view_processions',
            'view_police_stations', 'view_reports', 'generate_reports', 'view_alerts',
            'view_holding_points', 'view_visarjan_points', 'view_tracking_history', 'view_journey',
            'assign_field_officers', 'create_assignments', 'reassign_assignments', 'manage_assignments',
            'handover_duty', 'ingest_telemetry', 'view_officer_locations', 'manage_users',
            'manage_geography', 'export_reports', 'view_audit_logs', 'view_assignments',
        ]
    },
    {
        'role': 'ACP',
        'description': 'Assistant Commissioner of Police with supervisory authority over all police stations and processions within their division or zone.',
        'permissions': [
            'view_dashboard', 'view_live_map', 'view_gpids', 'view_idols', 'view_processions',
            'view_police_stations', 'view_reports', 'generate_reports', 'view_alerts',
            'view_holding_points', 'view_visarjan_points', 'view_tracking_history', 'view_journey',
            'assign_field_officers', 'create_assignments', 'reassign_assignments', 'view_officer_locations',
            'export_reports', 'view_assignments',
        ]
    },
    {
        'role': 'SHO',
        'description': 'Station House Officer with operational authority over idol processions, officer assignments, and live tracking within their police station.',
        'permissions': [
            'view_dashboard', 'view_live_map', 'view_gpids', 'view_idols', 'view_processions',
            'view_police_stations', 'view_reports', 'generate_reports', 'view_alerts',
            'view_holding_points', 'view_visarjan_points', 'view_tracking_history', 'view_journey',
            'assign_field_officers', 'create_assignments', 'reassign_assignments', 'view_officer_locations',
            'export_reports', 'view_assignments',
        ]
    },
    {
        'role': 'CONSTABLE',
        'description': 'Ground staff and field officer assigned to live idol tracking duties and GPS telemetry transmission.',
        'permissions': [
            'view_live_map', 'ingest_telemetry',
        ]
    },
]


def seed_templates_and_bootstrap_super_admin(apps, schema_editor):
    RolePermissionTemplate = apps.get_model('accounts', 'RolePermissionTemplate')
    User = apps.get_model('accounts', 'User')
    AuditEvent = apps.get_model('audit', 'AuditEvent')

    # 1. Seed Role Permission Templates
    for item in ROLE_DATA:
        RolePermissionTemplate.objects.get_or_create(
            role=item['role'],
            defaults={
                'permissions': item['permissions'],
                'description': item['description'],
            }
        )

    # 2. Bootstrap SuchithSara to SUPER_ADMIN safely
    target_user = User.objects.filter(username__iexact='SuchithSara').first()
    if target_user:
        if target_user.role != 'SUPER_ADMIN':
            old_role = target_user.role
            target_user.role = 'SUPER_ADMIN'
            target_user.save(update_fields=['role'])

            # Log SUPER_ADMIN_GRANTED audit event
            try:
                AuditEvent.objects.create(
                    actor=None,
                    action='SUPER_ADMIN_GRANTED',
                    target_model='User',
                    target_id=str(target_user.id),
                    details={
                        'username': target_user.username,
                        'full_name': f"{target_user.first_name} {target_user.last_name}".strip(),
                        'previous_role': old_role,
                        'new_role': 'SUPER_ADMIN',
                        'reason': 'Production bootstrap: designated primary Super Administrator',
                    }
                )
            except Exception:
                pass


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_rolepermissiontemplate'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_templates_and_bootstrap_super_admin, reverse_noop),
    ]
