"""
Pure server-side PDF Report generation using ReportLab.
Produces official Telangana / Hyderabad Police Ganesh Visarjan Live Tracking Journey Report.
"""
import io
import math
import uuid
from datetime import timedelta
from django.utils import timezone
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether, HRFlowable
)
from apps.idols.models import Idol
from apps.assignments.models import Assignment
from apps.tracking.models import TrackingSession, LocationPoint, IdolEvent
from apps.geography.models import BoundaryEvent


def haversine_km(lat1, lon1, lat2, lon2):
    R = 6371.0
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat / 2)**2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c


def get_height_badge(height):
    if height is None:
        return 'N/A'
    h = float(height)
    if 15.0 <= h < 21.0:
        return f"{h:.1f} ft (15–20 FT - GREEN)"
    elif 21.0 <= h < 26.0:
        return f"{h:.1f} ft (21–25 FT - YELLOW)"
    elif h >= 26.0:
        return f"{h:.1f} ft (26+ FT - RED)"
    return f"{h:.1f} ft (<15 FT Subthreshold)"


def generate_idol_pdf_report(gpid, generated_by_user=None):
    """
    Generates a formal police operational report for a specific GPID.
    Returns bytes of the PDF and report ID.
    """
    idol = Idol.objects.get(gpid__iexact=gpid)
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=17,
        alignment=1,
        textColor=colors.HexColor('#0F172A')
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=13,
        alignment=1,
        textColor=colors.HexColor('#1E3A8A')
    )
    meta_style = ParagraphStyle(
        'MetaStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=10,
        alignment=1,
        textColor=colors.HexColor('#64748B')
    )
    section_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=13,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=5,
        spaceBefore=8
    )
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#334155')
    )
    body_bold = ParagraphStyle(
        'BodyBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#0F172A')
    )

    elements = []

    # 1. Header & Official Metadata
    elements.append(Paragraph("TELANGANA POLICE DEPARTMENT - HYDERABAD COMMISSIONERATE", title_style))
    elements.append(Paragraph("GANESH VISARJAN LIVE TRACKING - OPERATIONAL INCIDENT REPORT", subtitle_style))

    report_id = f"HYD-REP-{uuid.uuid4().hex[:8].upper()}"
    now_str = timezone.localtime(timezone.now()).strftime('%d-%b-%Y %I:%M:%S %p IST')
    by_str = generated_by_user.username if generated_by_user else 'System Officer'
    role_str = getattr(generated_by_user, 'role', 'Authorized Officer') if generated_by_user else 'Authorized'

    meta_text = f"Report ID: <b>{report_id}</b> &nbsp;|&nbsp; Generated At: <b>{now_str}</b> &nbsp;|&nbsp; Generated By: <b>{by_str} ({role_str})</b>"
    elements.append(Spacer(1, 3))
    elements.append(Paragraph(meta_text, meta_style))
    elements.append(Spacer(1, 4))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#1E3A8A'), spaceBefore=2, spaceAfter=6))

    # 2. Key Operational Summary & Idol Specifications
    can_view_sensitive = bool(generated_by_user and getattr(generated_by_user, 'role', None) in ['MAIN_OFFICER', 'ACP', 'SHO'])
    contact_val = idol.raw_metadata.get('mobile_no', 'N/A') if (can_view_sensitive and idol.raw_metadata) else 'RESTRICTED (Station Officer+ Only)'

    origin_loc = f"{idol.address or ''} {idol.instal_street or ''} {idol.instal_village or ''}".strip() or idol.police_station
    destination_loc = idol.river_name or idol.lake_type or 'Designated Visarjan Point'

    elements.append(Paragraph("1. PRIMARY OPERATIONAL SPECIFICATIONS", section_style))
    idol_data = [
        [
            Paragraph("<b>GPID:</b>", body_style), Paragraph(f"<font color='#1E3A8A'><b>{idol.gpid}</b></font>", body_bold),
            Paragraph("<b>Procession State:</b>", body_style), Paragraph(f"<b>{idol.get_procession_state_display()}</b>", body_bold),
        ],
        [
            Paragraph("<b>Applicant / Organizer:</b>", body_style), Paragraph(idol.name or 'Individual', body_style),
            Paragraph("<b>Samithi / Association:</b>", body_style), Paragraph(idol.association_name or 'N/A', body_style),
        ],
        [
            Paragraph("<b>Contact Number:</b>", body_style), Paragraph(contact_val, body_style),
            Paragraph("<b>Idol Height / Class:</b>", body_style), Paragraph(get_height_badge(idol.idol_height), body_bold),
        ],
        [
            Paragraph("<b>Origin Jurisdiction:</b>", body_style), Paragraph(f"{idol.zone} Zone ({idol.police_station})", body_style),
            Paragraph("<b>Destination Waterbody:</b>", body_style), Paragraph(f"<font color='#0D9488'><b>{destination_loc}</b></font>", body_style),
        ],
        [
            Paragraph("<b>Immersion Date:</b>", body_style), Paragraph(str(idol.immersion_date) if idol.immersion_date else 'N/A', body_style),
            Paragraph("<b>Pandal Height:</b>", body_style), Paragraph(f"{idol.pandal_height} ft" if idol.pandal_height else 'N/A', body_style),
        ],
        [
            Paragraph("<b>Origin Location:</b>", body_style), Paragraph(origin_loc, body_style),
            "", ""
        ]
    ]

    t_idol = Table(idol_data, colWidths=[1.3 * inch, 2.2 * inch, 1.4 * inch, 2.1 * inch])
    t_idol.setStyle(TableStyle([
        ('SPAN', (1, 5), (3, 5)),
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 2.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
    ]))
    elements.append(t_idol)
    elements.append(Spacer(1, 6))

    # 3. Constable Assignment & Handover History
    elements.append(Paragraph("2. FIELD OFFICER ASSIGNMENT & HANDOVER CHRONOLOGY", section_style))
    assignments = Assignment.objects.filter(idol=idol).order_by('started_at').select_related('constable', 'assigned_by', 'handover_to')

    if assignments.exists():
        assign_rows = [[
            Paragraph("<b>Constable</b>", body_style),
            Paragraph("<b>Police ID</b>", body_style),
            Paragraph("<b>Started At</b>", body_style),
            Paragraph("<b>Ended At</b>", body_style),
            Paragraph("<b>Handover / Status</b>", body_style),
        ]]
        for a in assignments:
            start_str = timezone.localtime(a.started_at).strftime('%d-%b %H:%M') if a.started_at else 'N/A'
            end_str = timezone.localtime(a.ended_at).strftime('%d-%b %H:%M') if a.ended_at else 'ACTIVE'
            details = "ACTIVE ASSIGNMENT" if a.is_active else f"Handover to {a.handover_to.username if a.handover_to else 'N/A'}: {a.handover_reason}"
            assign_rows.append([
                Paragraph(a.constable.get_full_name() or a.constable.username, body_style),
                Paragraph(a.constable.police_id or 'N/A', body_style),
                Paragraph(start_str, body_style),
                Paragraph(end_str, body_style),
                Paragraph(details, body_style),
            ])
        t_assign = Table(assign_rows, colWidths=[1.5 * inch, 1.0 * inch, 1.1 * inch, 1.1 * inch, 2.3 * inch])
        t_assign.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('TOPPADDING', (0, 0), (-1, -1), 2.5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
            ('LEFTPADDING', (0, 0), (-1, -1), 5),
            ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ]))
        elements.append(t_assign)
    else:
        elements.append(Paragraph("No constable duty assignments recorded.", body_style))

    elements.append(Spacer(1, 6))

    # 4. GPS Procession Tracking Summary
    elements.append(Paragraph("3. GPS TRACKING & PROCESSION METRICS", section_style))
    points = list(LocationPoint.objects.filter(session__assignment__idol=idol).order_by('recorded_at'))
    total_pts = len(points)

    if total_pts > 0:
        first_pt = points[0]
        last_pt = points[-1]
        start_time = timezone.localtime(first_pt.recorded_at).strftime('%d-%b-%Y %I:%M:%S %p')
        last_time = timezone.localtime(last_pt.recorded_at).strftime('%d-%b-%Y %I:%M:%S %p')

        duration_sec = (last_pt.recorded_at - first_pt.recorded_at).total_seconds()
        duration_str = str(timedelta(seconds=int(duration_sec))) if duration_sec >= 0 else "0:00:00"

        # Calculate sequential travelled distance
        total_dist_km = 0.0
        for i in range(1, len(points)):
            seg = haversine_km(points[i-1].latitude, points[i-1].longitude, points[i].latitude, points[i].longitude)
            if seg >= 0.005:
                total_dist_km += seg

        speeds = [p.speed for p in points if p.speed is not None]
        max_speed = (max(speeds) * 3.6) if speeds else 0.0

        gps_data = [
            [
                Paragraph("<b>Total Breadcrumbs:</b>", body_style), Paragraph(str(total_pts), body_style),
                Paragraph("<b>Distance Travelled:</b>", body_style), Paragraph(f"<b>{total_dist_km:.2f} km</b>", body_bold),
            ],
            [
                Paragraph("<b>Tracking Started:</b>", body_style), Paragraph(start_time, body_style),
                Paragraph("<b>Journey Duration:</b>", body_style), Paragraph(duration_str, body_style),
            ],
            [
                Paragraph("<b>Latest GPS Update:</b>", body_style), Paragraph(last_time, body_style),
                Paragraph("<b>Max Speed Recorded:</b>", body_style), Paragraph(f"{max_speed:.1f} km/h", body_style),
            ],
            [
                Paragraph("<b>Start Coordinates:</b>", body_style), Paragraph(f"({first_pt.latitude:.5f}, {first_pt.longitude:.5f})", body_style),
                Paragraph("<b>Latest Coordinates:</b>", body_style), Paragraph(f"({last_pt.latitude:.5f}, {last_pt.longitude:.5f})", body_style),
            ]
        ]
        t_gps = Table(gps_data, colWidths=[1.3 * inch, 2.2 * inch, 1.4 * inch, 2.1 * inch])
        t_gps.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('TOPPADDING', (0, 0), (-1, -1), 2.5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
            ('LEFTPADDING', (0, 0), (-1, -1), 5),
            ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ]))
        elements.append(t_gps)
    else:
        elements.append(Paragraph("No active or historical GPS points recorded for this idol.", body_style))

    elements.append(Spacer(1, 6))

    # 5. Chronological Operational Timeline
    elements.append(Paragraph("4. CHRONOLOGICAL OPERATIONAL EVENT TIMELINE", section_style))

    # Combine IdolEvents and BoundaryEvents
    timeline_items = []

    for ev in IdolEvent.objects.filter(idol=idol):
        timeline_items.append({
            'time': ev.timestamp,
            'event': ev.get_event_type_display(),
            'lat': f"{ev.latitude:.5f}" if ev.latitude else "—",
            'lon': f"{ev.longitude:.5f}" if ev.longitude else "—",
            'zone': ev.zone or idol.zone,
        })

    for be in BoundaryEvent.objects.filter(idol=idol).select_related('police_station'):
        timeline_items.append({
            'time': be.timestamp,
            'event': f"PS Boundary {be.get_event_type_display()} ({be.police_station.ps_name})",
            'lat': f"{be.latitude:.5f}",
            'lon': f"{be.longitude:.5f}",
            'zone': be.police_station.zone,
        })

    # Sort chronological
    timeline_items.sort(key=lambda x: x['time'])

    if timeline_items:
        t_rows = [[
            Paragraph("<b>Timestamp (IST)</b>", body_style),
            Paragraph("<b>Operational Event</b>", body_style),
            Paragraph("<b>Latitude</b>", body_style),
            Paragraph("<b>Longitude</b>", body_style),
            Paragraph("<b>Zone / PS</b>", body_style),
        ]]
        for item in timeline_items[:30]:  # up to 30 events per single report
            t_str = timezone.localtime(item['time']).strftime('%d-%b %H:%M:%S')
            t_rows.append([
                Paragraph(t_str, body_style),
                Paragraph(item['event'], body_style),
                Paragraph(item['lat'], body_style),
                Paragraph(item['lon'], body_style),
                Paragraph(item['zone'], body_style),
            ])
        t_timeline = Table(t_rows, colWidths=[1.4 * inch, 2.3 * inch, 1.1 * inch, 1.1 * inch, 1.1 * inch])
        t_timeline.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('TOPPADDING', (0, 0), (-1, -1), 2.5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 2.5),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(t_timeline)
    else:
        elements.append(Paragraph(f"Within designated origin jurisdiction ({idol.police_station}). No inter-zone boundary transitions logged.", body_style))

    elements.append(Spacer(1, 10))

    # 6. Official Sign-off & Legal Notice
    footer_text = (
        "<i>This document is an official administrative operational record produced by the Hyderabad Police "
        "Ganesh Visarjan Live Tracking System. Generated in compliance with Telangana Police Department standards. "
        "Report snapshot represents operational telemetry state as of generation timestamp.</i>"
    )
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CBD5E1'), spaceBefore=4, spaceAfter=6))
    elements.append(Paragraph(footer_text, meta_style))

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes, report_id
