"""
Pure server-side PDF Report generation using ReportLab.
Produces official Telangana / Hyderabad Police Ganesh Visarjan Live Tracking Journey Report.
"""
import io
import uuid
from django.utils import timezone
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether, HRFlowable
)
from apps.idols.models import Idol
from apps.assignments.models import Assignment
from apps.tracking.models import TrackingSession, LocationPoint
from apps.geography.models import BoundaryEvent


def generate_idol_pdf_report(gpid, generated_by_user=None):
    """
    Generates a formal police operational report for a specific GPID.
    Returns bytes of the PDF.
    """
    idol = Idol.objects.get(gpid__iexact=gpid)
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=15,
        leading=18,
        alignment=1,
        textColor=colors.HexColor('#0F172A')
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        alignment=1,
        textColor=colors.HexColor('#1E3A8A')
    )
    meta_style = ParagraphStyle(
        'MetaStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=10,
        alignment=1,
        textColor=colors.HexColor('#64748B')
    )
    section_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=6,
        spaceBefore=10
    )
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#334155')
    )

    elements = []

    # 1. Header
    elements.append(Paragraph("TELANGANA POLICE DEPARTMENT - HYDERABAD COMMISSIONERATE", title_style))
    elements.append(Paragraph("GANESH VISARJAN LIVE TRACKING - OFFICIAL GPID REPORT", subtitle_style))

    report_id = f"HYD-REP-{uuid.uuid4().hex[:8].upper()}"
    now_str = timezone.localtime(timezone.now()).strftime('%d-%b-%Y %I:%M:%S %p IST')
    by_str = generated_by_user.username if generated_by_user else 'System Officer'
    role_str = generated_by_user.get_role_display() if generated_by_user else 'Authorized'

    meta_text = f"Report ID: <b>{report_id}</b> &nbsp;|&nbsp; Generated At: <b>{now_str}</b> &nbsp;|&nbsp; Generated By: <b>{by_str} ({role_str})</b>"
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(meta_text, meta_style))
    elements.append(Spacer(1, 8))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#1E3A8A'), spaceBefore=2, spaceAfter=8))

    # 2. GPID & Idol Master Specifications Table
    elements.append(Paragraph("1. IDOL MASTER SPECIFICATIONS", section_style))
    idol_data = [
        [
            Paragraph("<b>GPID:</b>", body_style), Paragraph(f"<font color='#1E3A8A'><b>{idol.gpid}</b></font>", body_style),
            Paragraph("<b>Status:</b>", body_style), Paragraph(f"<b>{idol.status}</b>", body_style),
        ],
        [
            Paragraph("<b>Organizer:</b>", body_style), Paragraph(idol.name or 'N/A', body_style),
            Paragraph("<b>Association:</b>", body_style), Paragraph(idol.association_name or 'N/A', body_style),
        ],
        [
            Paragraph("<b>Zone:</b>", body_style), Paragraph(idol.zone or 'N/A', body_style),
            Paragraph("<b>Division:</b>", body_style), Paragraph(idol.division or 'N/A', body_style),
        ],
        [
            Paragraph("<b>Police Station:</b>", body_style), Paragraph(f"{idol.police_station} ({idol.ps_code})", body_style),
            Paragraph("<b>Procession State:</b>", body_style), Paragraph(f"<b>{idol.get_procession_state_display()}</b>", body_style),
        ],
        [
            Paragraph("<b>Idol Height:</b>", body_style), Paragraph(f"{idol.idol_height} ft" if idol.idol_height else 'N/A', body_style),
            Paragraph("<b>Pandal Height:</b>", body_style), Paragraph(f"{idol.pandal_height} ft" if idol.pandal_height else 'N/A', body_style),
        ],
        [
            Paragraph("<b>Immersion Date:</b>", body_style), Paragraph(str(idol.immersion_date) if idol.immersion_date else 'N/A', body_style),
            Paragraph("<b>Immersion Site:</b>", body_style), Paragraph(idol.river_name or idol.lake_type or 'N/A', body_style),
        ],
        [
            Paragraph("<b>Address:</b>", body_style), Paragraph(f"{idol.address or ''} {idol.instal_street or ''} {idol.instal_village or ''} PIN: {idol.instal_pin or ''}".strip() or 'N/A', body_style),
            "", ""
        ]
    ]

    t_idol = Table(idol_data, colWidths=[1.1 * inch, 2.4 * inch, 1.1 * inch, 2.4 * inch])
    t_idol.setStyle(TableStyle([
        ('SPAN', (1, 6), (3, 6)),
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    elements.append(t_idol)
    elements.append(Spacer(1, 8))

    # 3. Constable Assignment & Handover History
    elements.append(Paragraph("2. CONSTABLE ASSIGNMENT & HANDOVER CHRONOLOGY", section_style))
    assignments = Assignment.objects.filter(idol=idol).order_by('started_at').select_related('constable', 'assigned_by', 'handover_to')

    if assignments.exists():
        assign_rows = [[
            Paragraph("<b>Constable</b>", body_style),
            Paragraph("<b>Police ID</b>", body_style),
            Paragraph("<b>Started At</b>", body_style),
            Paragraph("<b>Ended At</b>", body_style),
            Paragraph("<b>Status / Handover Details</b>", body_style),
        ]]
        for a in assignments:
            start_str = timezone.localtime(a.started_at).strftime('%d-%b %H:%M') if a.started_at else 'N/A'
            end_str = timezone.localtime(a.ended_at).strftime('%d-%b %H:%M') if a.ended_at else 'ACTIVE'
            details = "ACTIVE ASSIGNMENT" if a.is_active else f"Handed over to {a.handover_to.username if a.handover_to else 'N/A'}: {a.handover_reason}"
            assign_rows.append([
                Paragraph(a.constable.get_full_name() or a.constable.username, body_style),
                Paragraph(a.constable.police_id or 'N/A', body_style),
                Paragraph(start_str, body_style),
                Paragraph(end_str, body_style),
                Paragraph(details, body_style),
            ])
        t_assign = Table(assign_rows, colWidths=[1.5 * inch, 1.0 * inch, 1.1 * inch, 1.1 * inch, 2.3 * inch])
        t_assign.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 5),
            ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ]))
        elements.append(t_assign)
    else:
        elements.append(Paragraph("No constable duty assignments recorded.", body_style))

    elements.append(Spacer(1, 8))

    # 4. GPS Procession Tracking Summary
    elements.append(Paragraph("3. GPS TRACKING & PROCESSION METRICS", section_style))
    points = LocationPoint.objects.filter(session__assignment__idol=idol).order_by('recorded_at')
    total_pts = points.count()

    if total_pts > 0:
        first_pt = points.first()
        last_pt = points.last()
        start_time = timezone.localtime(first_pt.recorded_at).strftime('%d-%b-%Y %I:%M:%S %p')
        last_time = timezone.localtime(last_pt.recorded_at).strftime('%d-%b-%Y %I:%M:%S %p')

        speeds = [p.speed for p in points if p.speed is not None]
        max_speed = max(speeds) * 3.6 if speeds else 0.0

        gps_data = [
            [
                Paragraph("<b>Total Breadcrumbs:</b>", body_style), Paragraph(str(total_pts), body_style),
                Paragraph("<b>Max Speed Recorded:</b>", body_style), Paragraph(f"{max_speed:.1f} km/h", body_style),
            ],
            [
                Paragraph("<b>Tracking Started:</b>", body_style), Paragraph(start_time, body_style),
                Paragraph("<b>Latest GPS Update:</b>", body_style), Paragraph(last_time, body_style),
            ],
            [
                Paragraph("<b>Start Coordinates:</b>", body_style), Paragraph(f"({first_pt.latitude:.5f}, {first_pt.longitude:.5f})", body_style),
                Paragraph("<b>Latest Coordinates:</b>", body_style), Paragraph(f"({last_pt.latitude:.5f}, {last_pt.longitude:.5f})", body_style),
            ]
        ]
        t_gps = Table(gps_data, colWidths=[1.4 * inch, 2.1 * inch, 1.4 * inch, 2.1 * inch])
        t_gps.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ]))
        elements.append(t_gps)
    else:
        elements.append(Paragraph("No active or historical GPS points recorded for this idol.", body_style))

    elements.append(Spacer(1, 8))

    # 5. Police Station Boundary Crossings
    elements.append(Paragraph("4. POLICE STATION JURISDICTION CROSSINGS", section_style))
    events = BoundaryEvent.objects.filter(idol=idol).order_by('timestamp').select_related('police_station')

    if events.exists():
        event_rows = [[
            Paragraph("<b>Timestamp</b>", body_style),
            Paragraph("<b>Event</b>", body_style),
            Paragraph("<b>Police Station</b>", body_style),
            Paragraph("<b>Coordinates</b>", body_style),
        ]]
        for ev in events:
            ev_time = timezone.localtime(ev.timestamp).strftime('%d-%b %H:%M:%S')
            event_rows.append([
                Paragraph(ev_time, body_style),
                Paragraph(ev.event_type, body_style),
                Paragraph(ev.police_station.ps_name, body_style),
                Paragraph(f"({ev.latitude:.5f}, {ev.longitude:.5f})", body_style),
            ])
        t_ev = Table(event_rows, colWidths=[1.8 * inch, 1.2 * inch, 2.0 * inch, 2.0 * inch])
        t_ev.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F1F5F9')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ]))
        elements.append(t_ev)
    else:
        elements.append(Paragraph(f"Within designated origin jurisdiction ({idol.police_station}). No inter-station crossings logged.", body_style))

    elements.append(Spacer(1, 15))

    # 6. Official Sign-off & Notice
    footer_text = (
        "<i>This document is an official administrative operational record produced by the Hyderabad Police "
        "Ganesh Visarjan Live Tracking System. Generated in compliance with Telangana Police Department standards.</i>"
    )
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#CBD5E1'), spaceBefore=5, spaceAfter=8))
    elements.append(Paragraph(footer_text, meta_style))

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes, report_id
