# Generated by Django 5.2.17 on 2026-09-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('invalid_gpid_count', models.IntegerField(default=0)),
                ('duplicate_gpid_count', models.IntegerField(default=0)),
                ('invalid_ps_count', models.IntegerField(default=0)),
                ('summary_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpid', models.CharField(db_index=True, help_text='Authoritative GPID (e.g., HYDCMRZCMNR1749)', max_length=64, unique=True)),
                ('ref_no', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, help_text='Organizer/Applicant Name', max_length=255)),
                ('association_name', models.CharField(blank=True, max_length=255)),
                ('dist_name', models.CharField(default='HYDERABAD', max_length=100)),
                ('zone', models.CharField(db_index=True, max_length=100)),
                ('division', models.CharField(db_index=True, max_length=100)),
                ('police_station', models.CharField(db_index=True, max_length=100)),
                ('ps_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('instal_h_no', models.CharField(blank=True, max_length=100)),
                ('instal_street', models.CharField(blank=True, max_length=255)),
                ('instal_floor', models.CharField(blank=True, max_length=50)),
                ('instal_village', models.CharField(blank=True, max_length=255)),
                ('instal_pin', models.CharField(blank=True, max_length=20)),
                ('idol_height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pandal_height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('immersion_date', models.DateField(blank=True, null=True)),
                ('river_name', models.CharField(blank=True, max_length=150)),
                ('lake_type', models.CharField(blank=True, max_length=100)),
                ('idol_type', models.CharField(blank=True, max_length=100)),
                ('specify_type', models.CharField(blank=True, max_length=100)),
                ('idol_area_type', models.CharField(blank=True, max_length=100)),
                ('instal_from_date', models.DateField(blank=True, null=True)),
                ('instal_to_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='APPROVED', max_length=50)),
                ('procession_state', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('TRACKING', 'Tracking Started'), ('MOVING', 'In Transit / Moving'), ('HOLDING', 'Holding / Stoppage'), ('AT_VISARJAN', 'At Visarjan Site'), ('IMMERSION_COMPLETED', 'Immersion Completed')], db_index=True, default='NOT_STARTED', max_length=30)),
                ('raw_metadata', models.JSONField(blank=True, default=dict, help_text='Preserved raw source fields and restricted contact details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Idol',
                'verbose_name_plural': 'Idols',
                'ordering': ['gpid'],
                'indexes': [models.Index(fields=['zone', 'police_station'], name='idols_idol_zone_04ebac_idx'), models.Index(fields=['procession_state', 'status'], name='idols_idol_process_eafd1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('gpid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ref_no', models.CharField(blank=True, max_length=64)),
                ('ps_name', models.CharField(blank=True, max_length=100)),
                ('issue_type', models.CharField(choices=[('MISSING_GPID', 'Missing GPID'), ('DUPLICATE_GPID', 'Duplicate GPID'), ('INVALID_PS_CODE', 'Invalid Police Station Code'), ('VALIDATION_ERROR', 'Validation Error')], db_index=True, max_length=30)),
                ('error_message', models.TextField()),
                ('raw_row_data', models.JSONField(default=dict)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='idols.importrun')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
