# Generated by Django 5.2.9 on 2026-09-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idol',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idol',
            name='geocoding_confidence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idol',
            name='geocoding_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idol',
            name='geocoding_status',
            field=models.CharField(choices=[('NOT_GEOCODED', 'Not Geocoded'), ('GEOCODED', 'Geocoded (High Confidence)'), ('PARTIAL', 'Partial / Low Confidence'), ('UNRESOLVED', 'Unresolved')], db_index=True, default='NOT_GEOCODED', max_length=20),
        ),
        migrations.AddField(
            model_name='idol',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='idol',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
