# Generated by Django 5.2.9 on 2026-09-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_idol_geocoding_query_used_idol_geocoding_result_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='idol',
            index=models.Index(fields=['immersion_date'], name='idols_idol_immersi_9115c5_idx'),
        ),
        migrations.AddIndex(
            model_name='idol',
            index=models.Index(fields=['immersion_date', 'procession_state'], name='idols_idol_immersi_4cd560_idx'),
        ),
    ]
